### ISSUE TITLE
"list contains invalid format!"

### ISSUE THREAD

**Issue by robtro** [kpreid/shinysdr#12]
Any idea on where to start looking? I'm trying to use HackRF... this previously worked great with a standard RTLSDR stick.. 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1438, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1667, in _finishRequestBody
    self.allContentReceived()
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/web.py", line 117, in render_PUT
    self._cell.set(self.grparse(data))
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/values.py", line 145, in set
    return self._setter(self._ctor(value))
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/top.py", line 346, in set_unpaused
    self.__start_or_stop()
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/top.py", line 353, in __start_or_stop
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/top.py", line 332, in start
    super(Top, self).start(**kwargs)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 103, in start
    top_block_start_unlocked(self._tb, max_noutput_items)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 4585, in top_block_start_unlocked
    return _runtime_swig.top_block_start_unlocked(*args, **kwargs)
exceptions.RuntimeError: list contains invalid format!

CONFIG: 
config.devices.add(u'osmo',shinysdr.plugins.osmosdr.OsmoSDRDevice(''))

also tried OsmoSDRDevice("hackrf"), etc. 

Thanks in advance!

**Comment by ch0mik** [comment]
I got the same.

My installed version 

sudo apt-get install  git-core autoconf automake cmake build-essential libusb-dev libusb-1.0-0-dev libboost1.55-all-dev python2.7 libpulse-dev  python-setuptools  alsa-utils 

cd ~/
git clone git://git.osmocom.org/rtl-sdr.git
cd rtl-sdr
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig


cd ~/
git clone https://github.com/EliasOenal/multimonNG.git
cd multimonNG
mkdir build
cd build
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr ..
lub
qmake ../multimon-ng.pro
make
sudo make install
sudo ldconfig

cd ~/
git clone  http://gnuradio.org/git/gnuradio.git
cd gnuradio
mkdir build
cd build
cmake ../
make all
sudo make install
sudo ldconfig

cd ~/
git clone git://git.osmocom.org/gr-osmosdr
cd gr-osmosdr/
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

cd ~/
git clone https://github.com/kpreid/shinysdr
cd shinysdr
sudo ./fetch-js-deps.sh
python setup.py build
sudo python setup.py install
python -m shinysdr.main --create shinysdr.conf
sudo python -m shinysdr.main  shinysdr.conf
