### ISSUE TITLE
error during create file

### ISSUE THREAD

**Issue by ch0mik** [kpreid/shinysdr#18]
python -m shinysdr.main --create shinysdr.conf
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ShinySDR-0.0.0-py2.7.egg/shinysdr/main.py", line 37, in <module>
    from twisted.internet.task import react
ImportError: cannot import name react

**Comment by kpreid** [comment]
You hav a too-old version of Twisted installed. ShinySDR requires Twisted 12.3.0 or later.
