### ISSUE TITLE
ERROR:shinysdr:main function encountered error

### ISSUE THREAD

**Issue by mathisono** [kpreid/shinysdr#23]
pi@kj6dzbSDR ~/shinysdr $ python -m shinysdr.main config
INFO:shinysdr:Log opened.
linux; GNU C++ version 4.6.3; Boost_104900; UHD_003.004.002-0-unknown

gr-osmosdr v0.1.3-4-g42c66fdd (0.1.4git) gnuradio 3.7.5git-0-g2bb2b314
built-in source types: file fcd rtl rtl_tcp uhd hackrf rfspace
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Elonics E4000 tuner
INFO:shinysdr:Constructing flow graph...
Using Volk machine: generic
INFO:shinysdr:Flow graph: Switching RF source
INFO:shinysdr:Flow graph: Changing sample rates
INFO:shinysdr:Flow graph: Rebuilding connections
INFO:shinysdr:Flow graph: ...done reconnecting.
INFO:shinysdr:Restoring state...
INFO:shinysdr:Starting web server...
ERROR:shinysdr:main function encountered error
Traceback (most recent call last):
  File "/home/pi/shinysdr/shinysdr/main.py", line 52, in main
    react(go)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.0.0-py2.7-linux-armv6l.egg/twisted/internet/task.py", line 875, in react
    finished = main(_reactor, *argv)
  File "/home/pi/shinysdr/shinysdr/main.py", line 47, in go
    return _main_async(reactor, argv, _abort_for_test)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.0.0-py2.7-linux-armv6l.egg/twisted/internet/defer.py", line 1253, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.0.0-py2.7-linux-armv6l.egg/twisted/internet/defer.py", line 1107, in _inlineCallbacks
    result = g.send(result)
  File "/home/pi/shinysdr/shinysdr/main.py", line 120, in _main_async
    IService(maker(top, noteDirty)).setServiceParent(services)
  File "shinysdr/config.py", line 106, in make_service
    import shinysdr.web as lazy_web
  File "shinysdr/web.py", line 41, in <module>
    import txws
  File "/usr/local/lib/python2.7/dist-packages/txWS-0.9.1-py2.7.egg/txws.py", line 30, in <module>
    import six
exceptions.ImportError: No module named six

INFO:shinysdr:Main loop terminated.
pi@kj6dzbSDR ~/shinysdr $

**Comment by kpreid** [comment]
`six` is a Python module depended on by txWS; you need install it or fix whatever didn't include it in dependencies to automatically install.
